### ISSUE TITLE
Fatal error when launching the script: tried to create Proc object without a block 

### ISSUE THREAD

**Issue by rurza** [lord/pinboard-to-instapaper#2]
```
 bundle install                                                                     
Fetching gem metadata from https://rubygems.org/.......
Using bundler 2.3.26
Fetching multi_xml 0.5.5
Fetching multipart-post 1.2.0
Installing multipart-post 1.2.0
Installing multi_xml 0.5.5
Fetching faraday 0.8.8
Installing faraday 0.8.8
Fetching faraday_middleware 0.8.8
Installing faraday_middleware 0.8.8
Fetching pinboard_api 1.0.0
Installing pinboard_api 1.0.0
Bundle complete! 2 Gemfile dependencies, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

========================================================================================

ruby ./transfer.rb                                                               
/Users/adam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/faraday-0.8.8/lib/faraday.rb:10:in `new': tried to create Proc object without a block (ArgumentError)
	from /Users/adam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/faraday-0.8.8/lib/faraday.rb:10:in `new'
	from ./transfer.rb:5:in `<main>'
```

**Comment by lord** [comment]
haha this code is like 11 years old now, i'm not surprised it doesn't work any more :)
